/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as StatusRouteImport } from './routes/status'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated/connectors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedEnterpriseConsoleRouteImport } from './routes/_authenticated/enterprise-console'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated/runs'
import { Route as AuthenticatedSecurityScansRouteImport } from './routes/_authenticated/security-scans'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as Char126authInitiateRouteImport } from './routes/[~]auth.initiate'
import { Route as Char126oauthInitiateRouteImport } from './routes/[~]oauth.initiate'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAgentsSlugRouteImport } from './routes/_authenticated/agents/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnterpriseConsoleRoute =
  AuthenticatedEnterpriseConsoleRouteImport.update({
    id: '/enterprise-console',
    path: '/enterprise-console',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityScansRoute =
  AuthenticatedSecurityScansRouteImport.update({
    id: '/security-scans',
    path: '/security-scans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const Char126authInitiateRoute = Char126authInitiateRouteImport.update({
  id: '/~auth/initiate',
  path: '/~auth/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126oauthInitiateRoute = Char126oauthInitiateRouteImport.update({
  id: '/~oauth/initiate',
  path: '/~oauth/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsSlugRoute = AuthenticatedAgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/releases': typeof ReleasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/trust': typeof TrustRoute
  '/workflows': typeof WorkflowsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/enterprise-console': typeof AuthenticatedEnterpriseConsoleRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/security-scans': typeof AuthenticatedSecurityScansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/~auth/initiate': typeof Char126authInitiateRoute
  '/~oauth/initiate': typeof Char126oauthInitiateRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agents/$slug': typeof AuthenticatedAgentsSlugRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/analytics': typeof AnalyticsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/releases': typeof ReleasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/trust': typeof TrustRoute
  '/workflows': typeof WorkflowsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/enterprise-console': typeof AuthenticatedEnterpriseConsoleRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/security-scans': typeof AuthenticatedSecurityScansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/~auth/initiate': typeof Char126authInitiateRoute
  '/~oauth/initiate': typeof Char126oauthInitiateRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agents/$slug': typeof AuthenticatedAgentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/releases': typeof ReleasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/trust': typeof TrustRoute
  '/workflows': typeof WorkflowsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/enterprise-console': typeof AuthenticatedEnterpriseConsoleRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRoute
  '/_authenticated/security-scans': typeof AuthenticatedSecurityScansRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/~auth/initiate': typeof Char126authInitiateRoute
  '/~oauth/initiate': typeof Char126oauthInitiateRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/agents/$slug': typeof AuthenticatedAgentsSlugRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/agents'
    | '/analytics'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/community'
    | '/compare'
    | '/contact'
    | '/customers'
    | '/developers'
    | '/docs'
    | '/enterprise'
    | '/integrations'
    | '/knowledge'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/playground'
    | '/pricing'
    | '/releases'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/status'
    | '/studio'
    | '/templates'
    | '/trust'
    | '/workflows'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/approvals'
    | '/audit'
    | '/connectors'
    | '/dashboard'
    | '/deliveries'
    | '/enterprise-console'
    | '/playbook'
    | '/profile'
    | '/runs'
    | '/security-scans'
    | '/settings'
    | '/auth/callback'
    | '/~auth/initiate'
    | '/~oauth/initiate'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agents/$slug'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/agents'
    | '/analytics'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/community'
    | '/compare'
    | '/contact'
    | '/customers'
    | '/developers'
    | '/docs'
    | '/enterprise'
    | '/integrations'
    | '/knowledge'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/playground'
    | '/pricing'
    | '/releases'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/status'
    | '/studio'
    | '/templates'
    | '/trust'
    | '/workflows'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/approvals'
    | '/audit'
    | '/connectors'
    | '/dashboard'
    | '/deliveries'
    | '/enterprise-console'
    | '/playbook'
    | '/profile'
    | '/runs'
    | '/security-scans'
    | '/settings'
    | '/auth/callback'
    | '/~auth/initiate'
    | '/~oauth/initiate'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agents/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/agents'
    | '/analytics'
    | '/apps'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/community'
    | '/compare'
    | '/contact'
    | '/customers'
    | '/developers'
    | '/docs'
    | '/enterprise'
    | '/integrations'
    | '/knowledge'
    | '/marketplace'
    | '/mcp'
    | '/models'
    | '/playground'
    | '/pricing'
    | '/releases'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/status'
    | '/studio'
    | '/templates'
    | '/trust'
    | '/workflows'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/connectors'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/enterprise-console'
    | '/_authenticated/playbook'
    | '/_authenticated/profile'
    | '/_authenticated/runs'
    | '/_authenticated/security-scans'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/~auth/initiate'
    | '/~oauth/initiate'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/agents/$slug'
    | '/_authenticated/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PricingRoute: typeof PricingRoute
  ReleasesRoute: typeof ReleasesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  StatusRoute: typeof StatusRoute
  StudioRoute: typeof StudioRoute
  TemplatesRoute: typeof TemplatesRoute
  TrustRoute: typeof TrustRoute
  WorkflowsRoute: typeof WorkflowsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char126authInitiateRoute: typeof Char126authInitiateRoute
  Char126oauthInitiateRoute: typeof Char126oauthInitiateRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enterprise-console': {
      id: '/_authenticated/enterprise-console'
      path: '/enterprise-console'
      fullPath: '/enterprise-console'
      preLoaderRoute: typeof AuthenticatedEnterpriseConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security-scans': {
      id: '/_authenticated/security-scans'
      path: '/security-scans'
      fullPath: '/security-scans'
      preLoaderRoute: typeof AuthenticatedSecurityScansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/~auth/initiate': {
      id: '/~auth/initiate'
      path: '/~auth/initiate'
      fullPath: '/~auth/initiate'
      preLoaderRoute: typeof Char126authInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~oauth/initiate': {
      id: '/~oauth/initiate'
      path: '/~oauth/initiate'
      fullPath: '/~oauth/initiate'
      preLoaderRoute: typeof Char126oauthInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$slug': {
      id: '/_authenticated/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AuthenticatedAgentsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedEnterpriseConsoleRoute: typeof AuthenticatedEnterpriseConsoleRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRoute
  AuthenticatedSecurityScansRoute: typeof AuthenticatedSecurityScansRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAgentsSlugRoute: typeof AuthenticatedAgentsSlugRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedEnterpriseConsoleRoute: AuthenticatedEnterpriseConsoleRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRoute,
  AuthenticatedSecurityScansRoute: AuthenticatedSecurityScansRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAgentsSlugRoute: AuthenticatedAgentsSlugRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  EnterpriseRoute: EnterpriseRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PricingRoute: PricingRoute,
  ReleasesRoute: ReleasesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  StatusRoute: StatusRoute,
  StudioRoute: StudioRoute,
  TemplatesRoute: TemplatesRoute,
  TrustRoute: TrustRoute,
  WorkflowsRoute: WorkflowsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char126authInitiateRoute: Char126authInitiateRoute,
  Char126oauthInitiateRoute: Char126oauthInitiateRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
